### ISSUE TITLE
Texture not showing up

### ISSUE THREAD

**Issue by mmmmmmTots** [TheIllusiveC4/CulinaryConstruct#42] opened 2020-08-21 04:05 UTC
#### Versions (Be specific, do not write "latest"): 
* Culinary Construct: whatever version is made for 1.16.1
* Forge: 1.16.1
#### Steps to Reproduce:
1.put bread in culinary table
2.put ANY item in next 
3.observer it give the classic purple and black error texture
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment] 2020-08-21 04:15
You'll have to be more specific with your versions before I can assist you. Just saying "1.16.1" is not enough. For instance, the latest Forge is 32.0.108 and the latest Culinary Construct for 1.16.1 is 3.0.0.2. Which versions of these do you have?

**Comment by mmmmmmTots** [comment] 2020-08-21 04:29
32.0,018 so thats probably why the textures arent working

**Comment by mmmmmmTots** [comment] 2020-08-21 04:30
108 not 018

**Comment by TheIllusiveC4** [comment] 2020-08-21 05:36
And which version of Culinary Construct do you have?

**Comment by TheIllusiveC4** [comment] 2020-09-05 08:42
Unfortunately, using Forge 32.0.108 and Culinary Construct 1.16.1-3.0.0.2, I cannot reproduce this issue. I have tried loading the world normally, exiting and re-entering the world, exiting and re-entering the game, and the textures always appear for me. For those who are experiencing the issue, have you tested this with only Culinary Construct installed?

**Comment by Yupoman** [comment] 2020-09-18 23:44
I am 99% sure it is caused by other mods. While I was adding mods it worked fine, then it bugged, then it worked again, and then it bugged again.
The question is, by which?

**Comment by Yupoman** [comment] 2020-09-19 00:02
I don't know if it's any use but those errors appear in the log file
[log.txt](https://github.com/TheIllusiveC4/CulinaryConstruct/files/5248720/log.txt)

Full log file
[latest.log](https://github.com/TheIllusiveC4/CulinaryConstruct/files/5248722/latest.log)

debug (I don't know what this is but I'll leave it here)
[debug.log](https://github.com/TheIllusiveC4/CulinaryConstruct/files/5248726/debug.log)

Quark does not cause the problem, I tried removing it since it was one of the last to add

**Comment by Yupoman** [comment] 2020-09-21 20:38
Well this was easy, it is compatible with optifine

**Comment by TheIllusiveC4** [comment] 2020-09-21 20:50
@Yupoman Interesting. Thanks for finding that out and letting us know. If it's an Optifine compatibility issue, I don't think there's anything I can do to fix that on my end. It seems like it's messing up the model loading provided by Forge. I'm closing this issue for now, but if someone has a potential solution or is experiencing this issue _without_ Optifine, just let me know.

**Closed by TheIllusiveC4** 2020-09-21 20:50 UTC
Labels: bug, cannot reproduce
