### ISSUE TITLE
You can pipe anything in the bread slot

### ISSUE THREAD

**Issue by wrulfy** [TheIllusiveC4/CulinaryConstruct#16] opened 2018-08-11 21:45 UTC
There's a bug, with hoppers and the sandwich station. basically if you fill the 5 slot with food, then place a hopper facing the station and put in the hopper any other different food, it goes into the bread slot. In fact this way any item can go, but you won't be able to make a sandwich if that item isn't food. it can be further glitchy, as this works as long as you don't right click the station while the hopper is filling as it will then start sending items to the food slots, overwriting whatever ingredients were there.

**Comment by TheIllusiveC4** [comment] 2018-08-11 22:47
This is a more detailed report with some different scenarios, but is essentially a duplicate of [#7](https://github.com/TheIllusiveC4/CulinaryConstruct/issues/7).

**Closed by TheIllusiveC4** 2018-08-11 22:47 UTC
Labels: duplicate
