### ISSUE TITLE
Crashes on the server with 1.2.0

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/CulinaryConstruct#21] opened 2018-09-28 02:59 UTC
[crash-2018-09-27_22.55.31-server.txt](https://github.com/TheIllusiveC4/CulinaryConstruct/files/2426604/crash-2018-09-27_22.55.31-server.txt)
you might have issue. Not entirely sure whats doing it. it crashes during start up. Only tried it on the server currently, but I wouldn't think it happens on the client but I'll check it now

**Comment by Darkmega18** [comment] 2018-09-28 03:03
Ok. yeah, it loads just fine client side. I'll back date for now. and hopefully it's not just something else interfering with it.

**Comment by TheIllusiveC4** [comment] 2018-09-28 03:39
Duplicate of https://github.com/TheIllusiveC4/CulinaryConstruct/issues/20
Update to version 1.2.0.1 which I just released on Curse.

**Closed by TheIllusiveC4** 2018-09-28 03:39 UTC
Labels: duplicate
