### ISSUE TITLE
Does not display nutrition correctly

### ISSUE THREAD

**Issue by Dr-WeiAL** [TheIllusiveC4/CulinaryConstruct#62] opened 2022-04-15 12:54 UTC
#### Versions (Be specific, do not write "latest"):
* Culinary Construct: 4.3.0.0
* Forge: 40.0.49
#### Observed Behavior:
![image](https://user-images.githubusercontent.com/47446553/163572979-bcb86766-c837-46ed-b647-bf36592d133c.png)
#### Steps to Reproduce: 
1.make sandwiches

**Comment by TheIllusiveC4** [comment] 2022-04-15 13:21
Which mod are you using to add that nutrition information?

**Comment by Dr-WeiAL** [comment] 2022-04-15 13:25
> Which mod are you using to add that nutrition information?

appleskin 2.4.0

**Comment by TheIllusiveC4** [comment] 2022-04-17 10:44
Duplicate of https://github.com/TheIllusiveC4/CulinaryConstruct/issues/34

**Closed as completed by TheIllusiveC4** 2022-04-17 10:44 UTC
Labels: type: bug
